version: "3"
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - sonarnet

  python-app:
    build: .
    container_name: python-app
    networks:
      - sonarnet
    depends_on:
      - sonarqube

networks:
  sonarnet:
    driver: bridge
